dogfood:
  host: https://dogfood.instabase.com
  path: ib_annotation/data/fs/Prod Drive/datasets/ci-test-datasets-do-not-delete
  token: 9BYRiWj5ueaVU6Tknkn1LrceTX5Axm # TODO: use env variable

uat:
  host: https://uat.dogfood.instabase.com
  path: ib_annotation/data/fs/Prod Drive/datasets/ci-test-datasets-do-not-delete
  token: 9BYRiWj5ueaVU6Tknkn1LrceTX5Axm

prod:
  host: https://instabase.com
  path: ib_annotation/data/fs/Instabase Drive/datasets/ci-test-datasets-do-not-delete
  token: D6wRkvyg6RhfH0zxlPG8vk0eVusbX8

doc-insights-sandbox:
  host: https://doc-insights.aws.sandbox.instabase.com
  path: ib_annotation/data/fs/Prod Drive/datasets/ci-test-datasets-do-not-delete
  token: ZQ00QNF847FSRGxdOXPFPFtEJLoik9

gs-sandbox:
  host: https://gs.aws.sandbox.instabase.com/
  path: ib_annotation/data/fs/Prod Drive/datasets/ci-test-datasets-do-not-delete
  token: BFJGz5BCnmvDXvwrPyoMbsi1as0vuv

solution-eng:
  host: https://solution-eng.aws.sandbox.instabase.com/
  path: ib_annotation/data/fs/Prod Drive/datasets/ci-test-datasets-do-not-delete
  token: vDatMjJ3J294G701cv7TMabwBfx3Td