UberEatsReceipts:
  env:
    - dogfood
  model_project_path: ml_studio_models/uber_eats
  dataset_project_path: ml_studio_datasets/uber_eats
  time_limit: 1200 # 20 minutes
  config: &defaults
    adam_epsilon: 1.e-8
    batch_size: 2
    chunk_size: 510
    epochs: 10
    learning_rate: 5.e-5
    loss_agg_steps: 1
    max_grad_norm: 1
    optimizer_type: AdamW
    scheduler_type: constant_schedule_with_warmup
    stride: 64
    use_mixed_precision: true
    warmup: 0
    weight_decay: 0
    class_weights: false
    model_name: microsoft/layoutlm-base-uncased
  metrics:
    precision:
      date: 0.5
      total: 0.95
    recall:
      date: 0.5
      total: 0.95
    f1:
      date: 0.5
      total: 0.95


UberEatsReceiptsProd:
  env:
    - prod
  model_project_path: ml_studio_models_prod/uber_eats
  dataset_project_path: ml_studio_datasets_prod/uber_eats
  time_limit: 1500
  config:
    <<: *defaults
  metrics:
    precision:
      date: 0.5
      total: 0.95
    recall:
      date: 0.5
      total: 0.95
    f1:
      date: 0.5
      total: 0.95


UberEatsBERT:
  env: []
  model_project_path: ml_studio_models/uber_eats
  dataset_project_path: ml_studio_datasets/uber_eats
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 10
    model_name: bert-base-uncased
    pipeline_name: plain_sl
  metrics:
    precision:
      date: 0
      total: 0
    recall:
      date: 0
      total: 0
    f1:
      date: 0
      total: 0


NYDriversLicensesV2:
  env:
    - dogfood
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 15
    use_mixed_precision: false
    model_name: microsoft/layoutlmv2-base-uncased
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.4
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesEarlyStopping:
  env:
    - dogfood
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 50  # should early stop earlier
    model_name: microsoft/layoutlm-base-uncased
    early_stopping_patience: 2
    validation_set_size: 0.2
  metrics: # Lower metrics since the training set will be smaller
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesXLM:
  env:
    - dogfood
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 15
    use_mixed_precision: false
    model_name: microsoft/layoutxlm-base
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesV2Prod:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 1800
  config:
    <<: *defaults
    epochs: 15
    use_mixed_precision: false
    model_name: microsoft/layoutlmv2-base-uncased
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.4
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesEarlyStoppingProd:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 1800
  config:
    <<: *defaults
    epochs: 50  # should early stop earlier
    model_name: microsoft/layoutlm-base-uncased
    early_stopping_patience: 2
    validation_set_size: 0.2
  metrics: # Lower metrics since the training set will be smaller
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesXLMProd:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 1800
  config:
    <<: *defaults
    epochs: 15
    use_mixed_precision: false
    model_name: microsoft/layoutxlm-base
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesQA:
  env:
    - dogfood
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 2500
  config:
    <<: *defaults
    epochs: 10
    model_name: bert-base-uncased
    pipeline_name: single_qa
  metrics:
    precision:
      date: 0.5
      total: 0.5
    recall:
      date: 0.5
      total: 0.5
    f1:
      date: 0.5
      total: 0.5


NYDriversLicensesQAProd:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 2500
  config:
    <<: *defaults
    epochs: 10
    model_name: bert-base-uncased
    pipeline_name: single_qa
  metrics:
    precision:
      date: 0.5
      total: 0.5
    recall:
      date: 0.5
      total: 0.5
    f1:
      date: 0.5
      total: 0.5
