UberEatsReceipts:
  env:
    - dogfood
    - uat
  model_project_path: ml_studio_models/uber_eats
  dataset_project_path: ml_studio_datasets/uber_eats
  time_limit: 1200 # 20 minutes
  config: &defaults
    adam_epsilon: 1.e-8
    batch_size: 2
    chunk_size: 510
    epochs: 10
    learning_rate: 5.e-5
    loss_agg_steps: 1
    max_grad_norm: 1
    optimizer_type: AdamW
    scheduler_type: constant_schedule_with_warmup
    stride: 64
    use_mixed_precision: true
    warmup: 0
    weight_decay: 0
    class_weights: false
    model_name: microsoft/layoutlm-base-uncased

  metrics:
    precision:
      date: 0.5
      total: 0.95
    recall:
      date: 0.5
      total: 0.95
    f1:
      date: 0.5
      total: 0.95


UberEatsXLM:
  env: []  # TODO: tune hyperparameters to make it work
  model_project_path: ml_studio_models/uber_eats
  dataset_project_path: ml_studio_datasets/uber_eats
  time_limit: 1500 # 20 minutes
  config:
    <<: *defaults
    epochs: 13
    model_name: microsoft/layoutxlm-base
  metrics:
    precision:
      date: 0.6
      total: 0.6
    recall:
      date: 0.6
      total: 0.6
    f1:
      date: 0.6
      total: 0.6


UberEatsV2:
  env: []
  model_project_path: ml_studio_models/uber_eats
  dataset_project_path: ml_studio_datasets/uber_eats
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 10
    stride: 64
    chunk_size: 512
    model_name: microsoft/layoutlmv2-base-uncased
  metrics:
    precision:
      date: 0.6
      total: 0.6
    recall:
      date: 0.6
      total: 0.6
    f1:
      date: 0.6
      total: 0.6


UberEatsBERT:
  env: []  # TODO: tune hyperparameters to make it work
  model_project_path: ml_studio_models/uber_eats
  dataset_project_path: ml_studio_datasets/uber_eats
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 17
    model_name: bert-base-uncased
    pipeline_name: plain_sl
  metrics:
    precision:
      date: 0.6
      total: 0.6
    recall:
      date: 0.6
      total: 0.6
    f1:
      date: 0.6
      total: 0.6


NYDriversLicenses:
  env:
    - dogfood
    - uat
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 15
    model_name: microsoft/layoutlm-base-uncased
  metrics: # TODO stop assuming higher is better
    # TODO maybe transpose this?
    precision:
      DL Number: 0.8
      Name: 0.7
      Address: 0.9
    recall:
      DL Number: 0.8
      Name: 0.5
      Address: 0.9
    f1:
      DL Number: 0.8
      Name: 0.6
      Address: 0.8
