NYDriversLicenses:
  env:
    - dogfood
    - uat
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 1200 # 20 minutes
  config: &defaults
    adam_epsilon: 1.e-8
    batch_size: 2
    chunk_size: 510
    epochs: 6
    learning_rate: 5.e-5
    loss_agg_steps: 1
    max_grad_norm: 1
    optimizer_type: AdamW
    scheduler_type: constant_schedule_with_warmup
    stride: 64
    use_mixed_precision: true
    warmup: 0
    weight_decay: 0
    class_weights: 10
    model_name: microsoft/layoutlm-base-uncased
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesProd:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 1200
  config:
    <<: *defaults
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesV2:
  env:
    - dogfood
    - uat
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 1800 # 20 minutes
  config:
    <<: *defaults
    epochs: 10
    use_mixed_precision: false
    model_name: microsoft/layoutlmv2-base-uncased
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.4
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesEarlyStopping:
  env:
    - dogfood
    - uat
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 50  # should early stop earlier
    model_name: microsoft/layoutlm-base-uncased
    early_stopping_patience: 2
    validation_set_size: 0.2
  metrics: # Lower metrics since the training set will be smaller
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesXLM:
  env:
    - dogfood
    - uat
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 1200 # 20 minutes
  config:
    <<: *defaults
    epochs: 10
    use_mixed_precision: false
    model_name: microsoft/layoutxlm-base
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesV2Prod:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 1800
  config:
    <<: *defaults
    epochs: 10
    use_mixed_precision: false
    model_name: microsoft/layoutlmv2-base-uncased
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.4
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesEarlyStoppingProd:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 1800
  config:
    <<: *defaults
    epochs: 50  # should early stop earlier
    model_name: microsoft/layoutlm-base-uncased
    early_stopping_patience: 2
    validation_set_size: 0.2
  metrics: # Lower metrics since the training set will be smaller
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesXLMProd:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 1800
  config:
    <<: *defaults
    epochs: 10
    use_mixed_precision: false
    model_name: microsoft/layoutxlm-base
  metrics:
    precision:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    recall:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5
    f1:
      DL Number: 0.5
      Name: 0.5
      Address: 0.5


NYDriversLicensesQA:
  env:
    - dogfood
    - uat
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 2500
  config:
    <<: *defaults
    epochs: 10
    model_name: bert-base-uncased
    pipeline_name: single_qa
  metrics:
    # TODO: stablize metrics to a higher value
    precision:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1
    recall:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1
    f1:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1


NYDriversLicensesMQA:
  env:
    - dogfood
    - uat
  model_project_path: ml_studio_models/driver_licenses
  dataset_project_path: ml_studio_datasets/driver_licenses
  time_limit: 2500
  config:
    <<: *defaults
    epochs: 10
    model_name: instabase/laymqav1-base
    pipeline_name: laymqav1
  metrics:
    # TODO: stablize metrics to a higher value
    precision:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1
    recall:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1
    f1:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1


NYDriversLicensesQAProd:
  env:
    - prod
  model_project_path: ml_studio_models_prod/driver_licenses
  dataset_project_path: ml_studio_datasets_prod/driver_licenses
  time_limit: 2500
  config:
    <<: *defaults
    epochs: 10
    model_name: bert-base-uncased
    pipeline_name: single_qa
  metrics:
    # TODO: stablize metrics to a higher value
    precision:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1
    recall:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1
    f1:
      DL Number: 0.1
      Name: 0.1
      Address: 0.1


Classification:
  env:
    - dogfood
  package: ibformers_classification
  model_project_path: ml_studio_models/classification
  dataset_project_path: ml_studio_datasets/classification
  time_limit: 2500
  config:
    <<: *defaults
    chunk_size: 512
    batch_size: 2
    epochs: 5
    class_weights: 1
    model_name: microsoft/layoutlm-base-uncased
    pipeline_name: layoutlm_cls
    task_type: classification
  metrics:
    precision:
      paystub: 0.5
      invoice: 0.5
      resume: 0.5
      passport: 0.5
    recall:
      paystub: 0.5
      invoice: 0.5
      resume: 0.5
      passport: 0.5
    f1:
      paystub: 0.5
      invoice: 0.5
      resume: 0.5
      passport: 0.5


ClassificationProd:
  env:
    - prod
  package: ibformers_classification
  model_project_path: ml_studio_models_prod/classification
  dataset_project_path: ml_studio_datasets_prod/classification
  time_limit: 2500
  config:
    <<: *defaults
    chunk_size: 512
    batch_size: 2
    epochs: 5
    class_weights: 1
    model_name: microsoft/layoutlm-base-uncased
    pipeline_name: layoutlm_cls
    task_type: classification
  metrics:
    precision:
      paystub: 0.5
      invoice: 0.5
      resume: 0.5
      passport: 0.5
    recall:
      paystub: 0.5
      invoice: 0.5
      resume: 0.5
      passport: 0.5
    f1:
      paystub: 0.5
      invoice: 0.5
      resume: 0.5
      passport: 0.5


SplitClassification:
  env:
    - dogfood
  package: ibformers_classification
  model_project_path: ml_studio_models/split_classification
  dataset_project_path: ml_studio_datasets/split_classification
  time_limit: 2500
  config:
    <<: *defaults
    chunk_size: 512
    epochs: 10
    loss_agg_steps: 2
    class_weights: 1
    use_mixed_precision: false
    model_name: microsoft/layoutlm-base-uncased
    pipeline_name: layoutlm_sc
    task_type: split_classification
  metrics:
    splitter_precision:
      split: 0.5
      no-split: 0.5
    splitter_recall:
      split: 0.5
      no-split: 0.5
    splitter_f1:
      split: 0.5
      no-split: 0.5
    classifier_precision:
      paystub: 0.4
      bank_statement: 0.5
      invoice: 0.5
      resume: 0.5
      w2: 0.5
    classifier_recall:
      paystub: 0.4
      bank_statement: 0.5
      invoice: 0.5
      resume: 0.5
      w2: 0.5
    classifier_f1:
      paystub: 0.4
      bank_statement: 0.5
      invoice: 0.5
      resume: 0.5
      w2: 0.5


SplitClassificationProd:
  env:
    - prod
  package: ibformers_classification
  model_project_path: ml_studio_models_prod/split_classification
  dataset_project_path: ml_studio_datasets_prod/split_classification
  time_limit: 2500
  config:
    <<: *defaults
    chunk_size: 512
    epochs: 10
    loss_agg_steps: 2
    class_weights: 1
    use_mixed_precision: false
    model_name: microsoft/layoutlm-base-uncased
    pipeline_name: layoutlm_sc
    task_type: split_classification
  metrics:
    splitter_precision:
      split: 0.5
      no-split: 0.5
    splitter_recall:
      split: 0.5
      no-split: 0.5
    splitter_f1:
      split: 0.5
      no-split: 0.5
    classifier_precision:
      paystub: 0.4
      bank_statement: 0.5
      invoice: 0.5
      resume: 0.5
      w2: 0.5
    classifier_recall:
      paystub: 0.4
      bank_statement: 0.5
      invoice: 0.5
      resume: 0.5
      w2: 0.5
    classifier_f1:
      paystub: 0.4
      bank_statement: 0.5
      invoice: 0.5
      resume: 0.5
      w2: 0.5
